CKB.Lang = CKB.Lang or {}

-- Display names + ordering for the language selector
CKB.LangOrder = { "en", "fr", "de", "es", "ru", "it", "zhCN" }
CKB.LangNames = {
    en = "English",
    fr = "Français",
    de = "Deutsch",
    es = "Español",
    it = "Italiano",
    ru = "Русский",
    zhCN = "中文（简体）",
}

-- ── English (reference / fallback) ────────────────────

CKB.Lang.en = {
    title                = "Commands Key Binding",
    admin_button         = "Admin Panel — View/Edit Player Keybinds",
    command_label        = "Command:",
    command_placeholder  = "Type a command...",
    argument_label       = "Argument:",
    argument_placeholder = "Optional argument...",
    keybind_label        = "Key Bind:",
    save_keybind         = "Save Key Bind",
    invalid_chars        = "Invalid: Only alphanumeric, +, -, _, *, /, ! and spaces allowed.",
    command_blocked      = "This command is blocked.",
    enter_valid_command  = "Please enter a valid command.",
    select_key           = "Please select a key.",
    warn_overwrite       = 'The key "%s" is already bound to "%s" in the Keybind Manager. It will be overwritten.',
    warn_engine          = 'The key "%s" is already bound to "%s" in Garry\'s Mod. The engine bind will take priority over the Keybind Manager binding, causing the command not to work while the engine bind is active. It is recommended to choose a different key.',
    search_placeholder   = "Search keybinds...",
    col_command          = "Command",
    col_argument         = "Argument",
    col_key              = "Key",
    edit                 = "Edit",
    delete               = "Delete",
    error_title          = "Commands Key Binding — Error",
    ok                   = "OK",
    warning              = "WARNING",
    confirm_continue     = "Are you sure you want to continue?",
    cancel               = "Cancel",
    continue_anyway      = "Continue Anyway",
    edit_keybind_title   = "Edit Key Bind",
    save_changes         = "Save Changes",
    invalid_command      = "Invalid command.",
    profile_label        = "Profile:",
    tip_new              = "New profile",
    tip_clone            = "Clone current profile",
    tip_rename           = "Rename current profile",
    tip_delete           = "Delete current profile",
    tip_share            = "Share current profile with a player",
    clone                = "Clone",
    rename               = "Rename",
    share                = "Share",
    new_profile_title    = "New Profile",
    clone_profile_title  = "Clone Profile",
    copy_suffix          = " (Copy)",
    rename_profile_title = "Rename Profile",
    profile_name_ph      = "Profile name...",
    delete_profile_title = "Delete Profile",
    confirm_delete       = 'Are you sure you want to delete "%s"?\nThis action cannot be undone.',
    share_picker_title   = "Share Profile — Select Player",
    col_player           = "Player",
    col_steamid          = "SteamID",
    share_sent           = "Share request sent!",
    incoming_share_title = "Incoming Profile Share",
    share_incoming_msg   = '%s wants to share their profile "%s" with you (%d keybinds).\n\nIf you accept, it will be added as a new profile.',
    decline              = "Decline",
    accept               = "Accept",
    profile_received     = "Profile received!",
    share_accepted       = "%s accepted your shared profile!",
    share_declined       = "%s declined your shared profile.",
    share_not_allowed    = "You are not allowed to share profiles.",
    admin_panel_title    = "CKB — Admin Panel",
    online_players       = "Online Players",
    col_profiles         = "Profiles",
    col_active           = "Active",
    col_sharing          = "Sharing",
    refresh              = "Refresh",
    select_player_hint   = "Select a player to view their keybinds",
    enable_sharing       = "Enable Sharing",
    disable_sharing      = "Disable Sharing",
    keybinds_for         = "Keybinds — %s",
    active_suffix        = " (active)",
    admin_edit_title     = "Admin — Edit Keybind",
    save                 = "Save",
    blocked              = "BLOCKED",
    click_to_bind        = "Click to bind...",
    press_key            = "Press a key...",
    language_label       = "Language:",
    chat_prefix          = "[CKB] ",
}

-- ── Français ──────────────────────────────────────────

CKB.Lang.fr = {
    title                = "Raccourcis de Commandes",
    admin_button         = "Panneau Admin — Voir/Modifier les raccourcis des joueurs",
    command_label        = "Commande :",
    command_placeholder  = "Tapez une commande...",
    argument_label       = "Argument :",
    argument_placeholder = "Argument optionnel...",
    keybind_label        = "Touche :",
    save_keybind         = "Enregistrer le raccourci",
    invalid_chars        = "Invalide : seuls les caractères alphanumériques, +, -, _, *, /, ! et espaces sont autorisés.",
    command_blocked      = "Cette commande est bloquée.",
    enter_valid_command  = "Veuillez entrer une commande valide.",
    select_key           = "Veuillez choisir une touche.",
    warn_overwrite       = 'La touche "%s" est déjà attribuée à "%s" dans le gestionnaire. Elle sera remplacée.',
    warn_engine          = 'La touche "%s" est déjà liée à "%s" dans Garry\'s Mod. Le raccourci du moteur a la priorité, ce qui empêchera la commande de fonctionner tant qu\'il est actif. Il est recommandé de choisir une autre touche.',
    search_placeholder   = "Rechercher des raccourcis...",
    col_command          = "Commande",
    col_argument         = "Argument",
    col_key              = "Touche",
    edit                 = "Modifier",
    delete               = "Supprimer",
    error_title          = "Raccourcis de Commandes — Erreur",
    ok                   = "OK",
    warning              = "AVERTISSEMENT",
    confirm_continue     = "Voulez-vous vraiment continuer ?",
    cancel               = "Annuler",
    continue_anyway      = "Continuer quand même",
    edit_keybind_title   = "Modifier le raccourci",
    save_changes         = "Enregistrer",
    invalid_command      = "Commande invalide.",
    profile_label        = "Profil :",
    tip_new              = "Nouveau profil",
    tip_clone            = "Cloner le profil actuel",
    tip_rename           = "Renommer le profil actuel",
    tip_delete           = "Supprimer le profil actuel",
    tip_share            = "Partager le profil actuel avec un joueur",
    clone                = "Cloner",
    rename               = "Renommer",
    share                = "Partager",
    new_profile_title    = "Nouveau Profil",
    clone_profile_title  = "Cloner le Profil",
    copy_suffix          = " (Copie)",
    rename_profile_title = "Renommer le Profil",
    profile_name_ph      = "Nom du profil...",
    delete_profile_title = "Supprimer le Profil",
    confirm_delete       = 'Voulez-vous vraiment supprimer "%s" ?\nCette action est irréversible.',
    share_picker_title   = "Partager le Profil — Choisir un joueur",
    col_player           = "Joueur",
    col_steamid          = "SteamID",
    share_sent           = "Demande de partage envoyée !",
    incoming_share_title = "Partage de Profil Entrant",
    share_incoming_msg   = '%s souhaite partager son profil "%s" avec vous (%d raccourcis).\n\nSi vous acceptez, il sera ajouté comme nouveau profil.',
    decline              = "Refuser",
    accept               = "Accepter",
    profile_received     = "Profil reçu !",
    share_accepted       = "%s a accepté votre profil partagé !",
    share_declined       = "%s a refusé votre profil partagé.",
    share_not_allowed    = "Vous n'êtes pas autorisé à partager des profils.",
    admin_panel_title    = "CKB — Panneau Admin",
    online_players       = "Joueurs en ligne",
    col_profiles         = "Profils",
    col_active           = "Actif",
    col_sharing          = "Partage",
    refresh              = "Actualiser",
    select_player_hint   = "Sélectionnez un joueur pour voir ses raccourcis",
    enable_sharing       = "Activer le partage",
    disable_sharing      = "Désactiver le partage",
    keybinds_for         = "Raccourcis — %s",
    active_suffix        = " (actif)",
    admin_edit_title     = "Admin — Modifier le raccourci",
    save                 = "Enregistrer",
    blocked              = "BLOQUÉ",
    click_to_bind        = "Cliquez pour lier...",
    press_key            = "Appuyez sur une touche...",
    language_label       = "Langue :",
    chat_prefix          = "[CKB] ",
}

-- ── Deutsch ───────────────────────────────────────────

CKB.Lang.de = {
    title                = "Tastenbelegung für Befehle",
    admin_button         = "Admin-Panel — Spieler-Tastenbelegungen ansehen/bearbeiten",
    command_label        = "Befehl:",
    command_placeholder  = "Befehl eingeben...",
    argument_label       = "Argument:",
    argument_placeholder = "Optionales Argument...",
    keybind_label        = "Taste:",
    save_keybind         = "Tastenbelegung speichern",
    invalid_chars        = "Ungültig: Nur Buchstaben, Zahlen, +, -, _, *, /, ! und Leerzeichen erlaubt.",
    command_blocked      = "Dieser Befehl ist gesperrt.",
    enter_valid_command  = "Bitte gib einen gültigen Befehl ein.",
    select_key           = "Bitte wähle eine Taste.",
    warn_overwrite       = 'Die Taste "%s" ist bereits mit "%s" im Manager belegt. Sie wird überschrieben.',
    warn_engine          = 'Die Taste "%s" ist in Garry\'s Mod bereits mit "%s" belegt. Die Engine-Belegung hat Vorrang, wodurch der Befehl nicht funktioniert, solange sie aktiv ist. Es wird empfohlen, eine andere Taste zu wählen.',
    search_placeholder   = "Tastenbelegungen suchen...",
    col_command          = "Befehl",
    col_argument         = "Argument",
    col_key              = "Taste",
    edit                 = "Bearbeiten",
    delete               = "Löschen",
    error_title          = "Tastenbelegung für Befehle — Fehler",
    ok                   = "OK",
    warning              = "WARNUNG",
    confirm_continue     = "Möchtest du wirklich fortfahren?",
    cancel               = "Abbrechen",
    continue_anyway      = "Trotzdem fortfahren",
    edit_keybind_title   = "Tastenbelegung bearbeiten",
    save_changes         = "Änderungen speichern",
    invalid_command      = "Ungültiger Befehl.",
    profile_label        = "Profil:",
    tip_new              = "Neues Profil",
    tip_clone            = "Aktuelles Profil klonen",
    tip_rename           = "Aktuelles Profil umbenennen",
    tip_delete           = "Aktuelles Profil löschen",
    tip_share            = "Aktuelles Profil mit einem Spieler teilen",
    clone                = "Klonen",
    rename               = "Umbenennen",
    share                = "Teilen",
    new_profile_title    = "Neues Profil",
    clone_profile_title  = "Profil klonen",
    copy_suffix          = " (Kopie)",
    rename_profile_title = "Profil umbenennen",
    profile_name_ph      = "Profilname...",
    delete_profile_title = "Profil löschen",
    confirm_delete       = 'Möchtest du "%s" wirklich löschen?\nDiese Aktion kann nicht rückgängig gemacht werden.',
    share_picker_title   = "Profil teilen — Spieler auswählen",
    col_player           = "Spieler",
    col_steamid          = "SteamID",
    share_sent           = "Teilen-Anfrage gesendet!",
    incoming_share_title = "Eingehende Profilfreigabe",
    share_incoming_msg   = '%s möchte sein Profil "%s" mit dir teilen (%d Tastenbelegungen).\n\nWenn du annimmst, wird es als neues Profil hinzugefügt.',
    decline              = "Ablehnen",
    accept               = "Annehmen",
    profile_received     = "Profil erhalten!",
    share_accepted       = "%s hat dein geteiltes Profil angenommen!",
    share_declined       = "%s hat dein geteiltes Profil abgelehnt.",
    share_not_allowed    = "Du darfst keine Profile teilen.",
    admin_panel_title    = "CKB — Admin-Panel",
    online_players       = "Spieler online",
    col_profiles         = "Profile",
    col_active           = "Aktiv",
    col_sharing          = "Teilen",
    refresh              = "Aktualisieren",
    select_player_hint   = "Wähle einen Spieler, um seine Tastenbelegungen zu sehen",
    enable_sharing       = "Teilen aktivieren",
    disable_sharing      = "Teilen deaktivieren",
    keybinds_for         = "Tastenbelegungen — %s",
    active_suffix        = " (aktiv)",
    admin_edit_title     = "Admin — Tastenbelegung bearbeiten",
    save                 = "Speichern",
    blocked              = "GESPERRT",
    click_to_bind        = "Zum Belegen klicken...",
    press_key            = "Taste drücken...",
    language_label       = "Sprache:",
    chat_prefix          = "[CKB] ",
}

-- ── Español ───────────────────────────────────────────

CKB.Lang.es = {
    title                = "Asignación de Teclas",
    admin_button         = "Panel de Admin — Ver/Editar atajos de jugadores",
    command_label        = "Comando:",
    command_placeholder  = "Escribe un comando...",
    argument_label       = "Argumento:",
    argument_placeholder = "Argumento opcional...",
    keybind_label        = "Tecla:",
    save_keybind         = "Guardar atajo",
    invalid_chars        = "No válido: solo se permiten caracteres alfanuméricos, +, -, _, *, /, ! y espacios.",
    command_blocked      = "Este comando está bloqueado.",
    enter_valid_command  = "Por favor, introduce un comando válido.",
    select_key           = "Por favor, selecciona una tecla.",
    warn_overwrite       = 'La tecla "%s" ya está asignada a "%s" en el gestor. Se sobrescribirá.',
    warn_engine          = 'La tecla "%s" ya está asignada a "%s" en Garry\'s Mod. La asignación del motor tendrá prioridad, lo que impedirá que el comando funcione mientras esté activa. Se recomienda elegir otra tecla.',
    search_placeholder   = "Buscar atajos...",
    col_command          = "Comando",
    col_argument         = "Argumento",
    col_key              = "Tecla",
    edit                 = "Editar",
    delete               = "Eliminar",
    error_title          = "Asignación de Teclas — Error",
    ok                   = "OK",
    warning              = "ADVERTENCIA",
    confirm_continue     = "¿Seguro que quieres continuar?",
    cancel               = "Cancelar",
    continue_anyway      = "Continuar de todos modos",
    edit_keybind_title   = "Editar atajo",
    save_changes         = "Guardar cambios",
    invalid_command      = "Comando no válido.",
    profile_label        = "Perfil:",
    tip_new              = "Nuevo perfil",
    tip_clone            = "Clonar perfil actual",
    tip_rename           = "Renombrar perfil actual",
    tip_delete           = "Eliminar perfil actual",
    tip_share            = "Compartir perfil actual con un jugador",
    clone                = "Clonar",
    rename               = "Renombrar",
    share                = "Compartir",
    new_profile_title    = "Nuevo Perfil",
    clone_profile_title  = "Clonar Perfil",
    copy_suffix          = " (Copia)",
    rename_profile_title = "Renombrar Perfil",
    profile_name_ph      = "Nombre del perfil...",
    delete_profile_title = "Eliminar Perfil",
    confirm_delete       = '¿Seguro que quieres eliminar "%s"?\nEsta acción no se puede deshacer.',
    share_picker_title   = "Compartir Perfil — Seleccionar jugador",
    col_player           = "Jugador",
    col_steamid          = "SteamID",
    share_sent           = "¡Solicitud de compartir enviada!",
    incoming_share_title = "Perfil Compartido Entrante",
    share_incoming_msg   = '%s quiere compartir su perfil "%s" contigo (%d atajos).\n\nSi aceptas, se añadirá como un nuevo perfil.',
    decline              = "Rechazar",
    accept               = "Aceptar",
    profile_received     = "¡Perfil recibido!",
    share_accepted       = "¡%s aceptó tu perfil compartido!",
    share_declined       = "%s rechazó tu perfil compartido.",
    share_not_allowed    = "No tienes permiso para compartir perfiles.",
    admin_panel_title    = "CKB — Panel de Admin",
    online_players       = "Jugadores conectados",
    col_profiles         = "Perfiles",
    col_active           = "Activo",
    col_sharing          = "Compartir",
    refresh              = "Actualizar",
    select_player_hint   = "Selecciona un jugador para ver sus atajos",
    enable_sharing       = "Activar compartir",
    disable_sharing      = "Desactivar compartir",
    keybinds_for         = "Atajos — %s",
    active_suffix        = " (activo)",
    admin_edit_title     = "Admin — Editar atajo",
    save                 = "Guardar",
    blocked              = "BLOQUEADO",
    click_to_bind        = "Haz clic para asignar...",
    press_key            = "Pulsa una tecla...",
    language_label       = "Idioma:",
    chat_prefix          = "[CKB] ",
}

-- ── Russian ───────────────────────────────────────────
CKB.Lang.ru = {
    title                = "Привязка команд к клавишам",
    admin_button         = "Панель администратора — просмотр/редактирование привязок игроков",
    command_label        = "Команда:",
    command_placeholder  = "Введите команду...",
    argument_label       = "Аргумент:",
    argument_placeholder = "Необязательный аргумент...",
    keybind_label        = "Клавиша:",
    save_keybind         = "Сохранить привязку",
    invalid_chars        = "Недопустимые символы: разрешены только буквенно-цифровые символы, +, -, _, *, /, ! и пробелы.",
    command_blocked      = "Эта команда заблокирована.",
    enter_valid_command  = "Пожалуйста, введите допустимую команду.",
    select_key           = "Пожалуйста, выберите клавишу.",
    warn_overwrite       = 'Клавиша "%s" уже привязана к "%s" в менеджере привязок. Она будет перезаписана.',
    warn_engine          = 'Клавиша "%s" уже привязана к "%s" в Garry\'s Mod. Системная привязка Garry\'s Mod имеет приоритет над привязкой в менеджере, поэтому команда не будет работать, пока активна системная привязка. Рекомендуется выбрать другую клавишу.',
    search_placeholder   = "Поиск привязок...",
    col_command          = "Команда",
    col_argument         = "Аргумент",
    col_key              = "Клавиша",
    edit                 = "Редактировать",
    delete               = "Удалить",
    error_title          = "Привязка команд к клавишам — Ошибка",
    ok                   = "OK",
    warning              = "ПРЕДУПРЕЖДЕНИЕ",
    confirm_continue     = "Вы уверены, что хотите продолжить?",
    cancel               = "Отмена",
    continue_anyway      = "Всё равно продолжить",
    edit_keybind_title   = "Редактировать привязку",
    save_changes         = "Сохранить изменения",
    invalid_command      = "Недопустимая команда.",
    profile_label        = "Профиль:",
    tip_new              = "Новый профиль",
    tip_clone            = "Клонировать текущий профиль",
    tip_rename           = "Переименовать текущий профиль",
    tip_delete           = "Удалить текущий профиль",
    tip_share            = "Поделиться текущим профилем с игроком",
    clone                = "Клонировать",
    rename               = "Переименовать",
    share                = "Поделиться",
    new_profile_title    = "Новый профиль",
    clone_profile_title  = "Клонировать профиль",
    copy_suffix          = " (Копия)",
    rename_profile_title = "Переименовать профиль",
    profile_name_ph      = "Имя профиля...",
    delete_profile_title = "Удалить профиль",
    confirm_delete       = 'Вы уверены, что хотите удалить "%s"?\nЭто действие нельзя отменить.',
    share_picker_title   = "Поделиться профилем — Выберите игрока",
    col_player           = "Игрок",
    col_steamid          = "SteamID",
    share_sent           = "Профиль отправлен!",
    incoming_share_title = "Получен профиль",
    share_incoming_msg   = '%s хочет поделиться с вами профилем "%s" (%d привязок).\n\nЕсли вы примете его, профиль будет добавлен как новый.',
    decline              = "Отклонить",
    accept               = "Принять",
    profile_received     = "Профиль получен!",
    share_accepted       = "%s принял ваш профиль!",
    share_declined       = "%s отклонил ваш профиль.",
    share_not_allowed    = "У вас нет разрешения на обмен профилями.",
    admin_panel_title    = "CKB — Панель администратора",
    online_players       = "Игроки онлайн",
    col_profiles         = "Профили",
    col_active           = "Активный",
    col_sharing          = "Обмен",
    refresh              = "Обновить",
    select_player_hint   = "Выберите игрока, чтобы просмотреть его привязки",
    enable_sharing       = "Разрешить обмен профилями",
    disable_sharing      = "Запретить обмен профилями",
    keybinds_for         = "Привязки — %s",
    active_suffix        = " (активный)",
    admin_edit_title     = "Администратор — Редактировать привязку",
    save                 = "Сохранить",
    blocked              = "ЗАБЛОКИРОВАНО",
    click_to_bind        = "Нажмите, чтобы назначить клавишу...",
    press_key            = "Нажмите клавишу...",
    language_label       = "Язык:",
    chat_prefix          = "[CKB] ",
}

-- ── Chinese (Simplified) ─────────────────────────────────────────
CKB.Lang.zhCN = {
    title                = "按键绑定",
    admin_button         = "管理员面板 — 查看/编辑玩家绑定",
    command_label        = "命令：",
    command_placeholder  = "输入命令...",
    argument_label       = "参数：",
    argument_placeholder = "可选参数...",
    keybind_label        = "按键：",
    save_keybind         = "保存绑定",
    invalid_chars        = "包含无效字符：仅允许字母、数字、+、-、_、*、/、! 和空格。",
    command_blocked      = "此命令已被禁止。",
    enter_valid_command  = "请输入有效的命令。",
    select_key           = "请选择一个按键。",
    warn_overwrite       = '按键“%s”已绑定到“%s”，将会被覆盖。',
    warn_engine          = '按键“%s”已在 Garry\'s Mod 中绑定到“%s”。游戏自身的按键绑定优先于本管理器，因此只要该绑定存在，此命令将无法生效。建议选择其他按键。',
    search_placeholder   = "搜索绑定...",
    col_command          = "命令",
    col_argument         = "参数",
    col_key              = "按键",
    edit                 = "编辑",
    delete               = "删除",
    error_title          = "按键绑定 - 错误",
    ok                   = "确定",
    warning              = "警告",
    confirm_continue     = "确定要继续吗？",
    cancel               = "取消",
    continue_anyway      = "仍然继续",
    edit_keybind_title   = "编辑绑定",
    save_changes         = "保存更改",
    invalid_command      = "无效的命令。",
    profile_label        = "配置：",
    tip_new              = "新建配置",
    tip_clone            = "复制当前配置",
    tip_rename           = "重命名当前配置",
    tip_delete           = "删除当前配置",
    tip_share            = "与玩家分享当前配置",
    clone                = "复制",
    rename               = "重命名",
    share                = "分享",
    new_profile_title    = "新建配置",
    clone_profile_title  = "复制配置",
    copy_suffix          = "（副本）",
    rename_profile_title = "重命名配置",
    profile_name_ph      = "配置名称...",
    delete_profile_title = "删除配置",
    confirm_delete       = '确定要删除“%s”吗？\n此操作无法撤销。',
    share_picker_title   = "分享配置 - 选择玩家",
    col_player           = "玩家",
    col_steamid          = "SteamID",
    share_sent           = "分享请求已发送！",
    incoming_share_title = "收到配置分享",
    share_incoming_msg   = '%s 想与你分享配置“%s”（%d 个绑定）。\n\n接受后，它将作为新的配置添加。',
    decline              = "拒绝",
    accept               = "接受",
    profile_received     = "配置已接收！",
    share_accepted       = "%s 已接受你的配置！",
    share_declined       = "%s 拒绝了你的配置。",
    share_not_allowed    = "你没有权限分享配置。",
    admin_panel_title    = "CKB - 管理员面板",
    online_players       = "在线玩家",
    col_profiles         = "配置",
    col_active           = "当前",
    col_sharing          = "分享",
    refresh              = "刷新",
    select_player_hint   = "选择一名玩家以查看其按键绑定",
    enable_sharing       = "允许分享",
    disable_sharing      = "禁止分享",
    keybinds_for         = "%s 的按键绑定",
    active_suffix        = "（当前）",
    admin_edit_title     = "管理员 - 编辑绑定",
    save                 = "保存",
    blocked              = "已禁用",
    click_to_bind        = "点击以绑定按键...",
    press_key            = "请按下一个按键...",
    language_label       = "语言：",
    chat_prefix          = "[CKB] ",
}

-- Italiano ────────────────────────────────────────────
CKB.Lang.it = {
    title                = "Associazione dei tasti",
    admin_button         = "Pannello amministratore — Visualizza/modifica le associazioni dei giocatori",
    command_label        = "Comando:",
    command_placeholder  = "Inserisci un comando...",
    argument_label       = "Argomento:",
    argument_placeholder = "Argomento opzionale...",
    keybind_label        = "Tasto:",
    save_keybind         = "Salva associazione",
    invalid_chars        = "Caratteri non validi: sono consentiti solo caratteri alfanumerici, +, -, _, *, /, ! e spazi.",
    command_blocked      = "Questo comando è bloccato.",
    enter_valid_command  = "Inserisci un comando valido.",
    select_key           = "Seleziona un tasto.",
    warn_overwrite       = 'Il tasto "%s" è già associato a "%s" nel gestore delle associazioni. Verrà sovrascritto.',
    warn_engine          = 'Il tasto "%s" è già associato a "%s" in Garry\'s Mod. L\'associazione del gioco ha la priorità su quella del gestore, quindi il comando non funzionerà finché l\'associazione del gioco sarà attiva. Si consiglia di scegliere un altro tasto.',
    search_placeholder   = "Cerca associazioni...",
    col_command          = "Comando",
    col_argument         = "Argomento",
    col_key              = "Tasto",
    edit                 = "Modifica",
    delete               = "Elimina",
    error_title          = "Associazione dei tasti - Errore",
    ok                   = "OK",
    warning              = "ATTENZIONE",
    confirm_continue     = "Sei sicuro di voler continuare?",
    cancel               = "Annulla",
    continue_anyway      = "Continua comunque",
    edit_keybind_title   = "Modifica associazione",
    save_changes         = "Salva modifiche",
    invalid_command      = "Comando non valido.",
    profile_label        = "Profilo:",
    tip_new              = "Nuovo profilo",
    tip_clone            = "Clona il profilo corrente",
    tip_rename           = "Rinomina il profilo corrente",
    tip_delete           = "Elimina il profilo corrente",
    tip_share            = "Condividi il profilo corrente con un giocatore",
    clone                = "Clona",
    rename               = "Rinomina",
    share                = "Condividi",
    new_profile_title    = "Nuovo profilo",
    clone_profile_title  = "Clona profilo",
    copy_suffix          = " (Copia)",
    rename_profile_title = "Rinomina profilo",
    profile_name_ph      = "Nome del profilo...",
    delete_profile_title = "Elimina profilo",
    confirm_delete       = 'Sei sicuro di voler eliminare "%s"?\nQuesta azione non può essere annullata.',
    share_picker_title   = "Condividi profilo - Seleziona un giocatore",
    col_player           = "Giocatore",
    col_steamid          = "SteamID",
    share_sent           = "Richiesta di condivisione inviata!",
    incoming_share_title = "Condivisione profilo in arrivo",
    share_incoming_msg   = '%s vuole condividere con te il profilo "%s" (%d associazioni).\n\nSe accetti, verrà aggiunto come nuovo profilo.',
    decline              = "Rifiuta",
    accept               = "Accetta",
    profile_received     = "Profilo ricevuto!",
    share_accepted       = "%s ha accettato il tuo profilo condiviso!",
    share_declined       = "%s ha rifiutato il tuo profilo condiviso.",
    share_not_allowed    = "Non hai il permesso di condividere i profili.",
    admin_panel_title    = "CKB - Pannello amministratore",
    online_players       = "Giocatori online",
    col_profiles         = "Profili",
    col_active           = "Attivo",
    col_sharing          = "Condivisione",
    refresh              = "Aggiorna",
    select_player_hint   = "Seleziona un giocatore per visualizzare le sue associazioni",
    enable_sharing       = "Abilita condivisione",
    disable_sharing      = "Disabilita condivisione",
    keybinds_for         = "Associazioni - %s",
    active_suffix        = " (attivo)",
    admin_edit_title     = "Amministratore - Modifica associazione",
    save                 = "Salva",
    blocked              = "BLOCCATO",
    click_to_bind        = "Clicca per associare...",
    press_key            = "Premi un tasto...",
    language_label       = "Lingua:",
    chat_prefix          = "[CKB] ",
}

-- ── Selection state (persisted via client convar) ─────

local langConVar = CreateClientConVar("ckb_language", "en", true, false, "Language for the Commands Key Binding UI")

local function resolveLang(code)
    if code and CKB.Lang[code] then return code end
    return "en"
end

CKB.CurrentLang = resolveLang(langConVar:GetString())

-- ── Lookup ────────────────────────────────────────────

function CKB.L(key, ...)
    local tbl = CKB.Lang[CKB.CurrentLang] or CKB.Lang.en
    local str = tbl[key]
    if str == nil then str = CKB.Lang.en[key] end
    if str == nil then return key end

    if select("#", ...) > 0 then
        local ok, formatted = pcall(string.format, str, ...)
        if ok then return formatted end
    end
    return str
end

-- ── Change language (rebuilds open UI) ────────────────

function CKB.SetLanguage(code)
    code = resolveLang(code)
    if code == CKB.CurrentLang then return end

    CKB.CurrentLang = code
    langConVar:SetString(code)

    -- Rebuild any open windows so the new language takes effect immediately.
    local reopenMain = IsValid(CKB.Frame)
    if IsValid(CKB.AdminFrame) then CKB.AdminFrame:Close() end
    if IsValid(CKB.Frame) then CKB.Frame:Close() end
    if reopenMain and CKB.OpenConfigMenu then CKB.OpenConfigMenu() end
end
