-- Commands Key Binding - Server loader

-- Register net strings
util.AddNetworkString("CKB_Config")
util.AddNetworkString("CKB_Update")
util.AddNetworkString("CKB_ProfileList")
util.AddNetworkString("CKB_ProfileSwitch")
util.AddNetworkString("CKB_ProfileCreate")
util.AddNetworkString("CKB_ProfileDelete")
util.AddNetworkString("CKB_ProfileRename")
util.AddNetworkString("CKB_ShareProfile")
util.AddNetworkString("CKB_ShareIncoming")
util.AddNetworkString("CKB_ShareAccept")
util.AddNetworkString("CKB_ShareDecline")
util.AddNetworkString("CKB_ShareResult")
util.AddNetworkString("CKB_AdminGetPlayers")
util.AddNetworkString("CKB_AdminPlayerList")
util.AddNetworkString("CKB_AdminGetBinds")
util.AddNetworkString("CKB_AdminBindsData")
util.AddNetworkString("CKB_AdminUpdateBind")
util.AddNetworkString("CKB_AdminToggleSharing")

-- Add client files
AddCSLuaFile("commands_keybinding/client/config.lua")
AddCSLuaFile("commands_keybinding/client/lang.lua")
AddCSLuaFile("commands_keybinding/client/theme.lua")
AddCSLuaFile("commands_keybinding/client/blocked.lua")
AddCSLuaFile("commands_keybinding/client/allcommands.lua")
AddCSLuaFile("commands_keybinding/client/suggestions.lua")
AddCSLuaFile("commands_keybinding/client/net.lua")
AddCSLuaFile("commands_keybinding/client/popups.lua")
AddCSLuaFile("commands_keybinding/client/profiles_ui.lua")
AddCSLuaFile("commands_keybinding/client/sharing_ui.lua")
AddCSLuaFile("commands_keybinding/client/admin_ui.lua")
AddCSLuaFile("commands_keybinding/client/menu.lua")
AddCSLuaFile("commands_keybinding/client/binds.lua")

-- Load server modules
include("commands_keybinding/server/data.lua")
include("commands_keybinding/server/sharing.lua")
include("commands_keybinding/server/admin.lua")
include("commands_keybinding/server/net.lua")
